#include "SPI.h"

void SPI_INIT(void) 
	{
		SPI1->CR1 = 0;
		SPI1->CR1 &= ~(SPI_CR1_CPOL | SPI_CR1_CPHA);
		SPI1->CR1 |= SPI_CR1_MSTR;
		SPI1->CR1 |= SPI_CR1_BR_0;
		SPI1->CR1 &= ~SPI_CR1_LSBFIRST;
		SPI1->CR1 &= ~SPI_CR1_DFF;
		SPI1->CR1 |= SPI_CR1_SSM | SPI_CR1_SSI;
		SPI1->CR1 &= ~SPI_CR1_CRCNEXT;
		SPI1->CR1 &= ~SPI_CR1_CRCEN;
		SPI1->CR1 &= ~SPI_CR1_RXONLY;
		SPI1->CR1 &= ~SPI_CR1_BIDIMODE;
		SPI1->CR1 |= SPI_CR1_SPE;
		
		SPI1->CR2 &= ~SPI_CR2_RXDMAEN;
		SPI1->CR2 &= ~SPI_CR2_TXDMAEN;
		SPI1->CR2 &= ~SPI_CR2_SSOE;
		SPI1->CR2 &= ~SPI_CR2_ERRIE;
		SPI1->CR2 &= ~SPI_CR2_RXNEIE;
		SPI1->CR2 &= ~SPI_CR2_TXEIE;
	}
